### ISSUE TITLE
Redo website

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#147]
* The URL in the description is not working
* There are some sources in the `website/` folder but:
   * They use `hyde`, which is not Python3-compatible

Plan of action:
* Use just sphinx
* Deploy on GitHub pages instead

**Comment by dmerejkowsky** [comment]
TODO:

* [ ] Configure repo with a secret so that deployment works automatically
* [ ] Convert remaining html files in website/contents/ to RST and include them 
* [ ] Convert the hyde theme to a sphinx theme (optional)

**Comment by dmerejkowsky** [comment]
For reference, here's what the old menu looked like:

```yaml
name: Home
description: Home Page

name: Download
description: Download

name: Tutorial
description: Tutorial

name: API
description: API Reference

name: Code
description: Code
url: > https://github.com/rfk/pyenchant/
```
